level-price: 5
blocks-for-level: 25
 
start-items:
 - axe_1
 
locked-chest:
 items:
  STONE:
   name: '&aКамушек'
   chance: 80
  DIAMOND: 
   chance: 2
  DIRT: 
   chance: 5
  GRASS: 
   chance: 10
   name: 'Травушка'
 
mobs:
 skeleton:
  name: 'Наездник #<3'
  damage: 5
  health: 25
  knockback: 3
  shoot-delay: 50
 spider: 
  name: '&cПаук #<3'
  health: 50
  damage: 5
  money: 10
  speed: 3
  jumpdelay: 150
  drop:  
 zombiegiant: 
  name: '&cПаук #<3'
  health: 500
  damage: 5
  money: 100
  speed: 3
  drop: 
 rat:
  health: 5
  name: 'Тюремная крыса #<3'
  damage: 2
  speed: 2
 zombie:
  health: 50
  name: 'Зомби #<3'
  damage: 6
  speed: 3
 bigslime: 
  name: '&cСлизняк #<3'
  health: 300
  damage: 15
  speed: 6
  money: 750
  drop:
 tinyslime: 
  name: '&cМаленький слизняк'
  health: 25
  damage: 5